#!/bin/sh
#
# wordlists2c.sh - shellscript to translate wordlist.txt to c file
#
# Copyright 2020 Rik Snel <rik@snel.it>
#
# This file is part of slip0039.
#
# slip0039 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# slip0039 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with slip0039.  If not, see <https://www.gnu.org/licenses/>.

fatal() {
	echo $1 >&2
	exit 1
}

if [ "$#" != "0" ]; then
	fatal "wrong number of arguments given"
fi

if ! command -v sha256sum >/dev/null && command -v shasum >/dev/null; then
	sha256sum() { shasum -a 256 "$@"; }
fi

INIT="void wordlists_init() {\n"

# filename_prefix sha256 lines
format_wordlist() {
	FILENAME=wordlists/wordlist_$1.txt
	if [ ! -f "$FILENAME" ]; then
		fatal "file \"$FILENAME\" not found"
	fi

	if [ ! -r "$FILENAME" ]; then
		fatal "file \"$FILENAME\" is not readable"
	fi

	if [ "$2" != `sha256sum "$FILENAME" | cut -f 1 -d ' '` ]; then
		fatal "sha256sum of \"$FILENAME\" does not match"
	fi

	NUM=`wc -l $FILENAME | awk '{print $1}'`

	if [ "$NUM" != "$3" ]; then
		fatal "file $FILENAME has $NUM lines, when $3 lines were expected"
	fi

	# use LANG=C to get the bytecount of word lenght instead of character count
	MAX_WORD_LENGTH=`LANG=C awk -vmax=0 'length($0) > max {max = length($0)} END {print max}' < "$FILENAME"`
	MIN_WORD_LENGTH=`LANG=C awk -vmin=255 'length($0) < min {min = length($0)} END {print min}' < "$FILENAME"`
	echo
	echo wordlist_t wordlist_$1 = {
	echo "\t.name = \"$1\","
	echo "\t.max_word_length = $MAX_WORD_LENGTH,"
	echo "\t.min_word_length = $MIN_WORD_LENGTH,"
	echo "\t.words = (char *[]){"
	sed "s/^/\t\t\"/;s/\$/\",/" < "$FILENAME"
	echo "\t}"
	echo "};"
	echo
	INIT="$INIT\tfixnum_multiplier16_init(&wordlist_$1.m, $3);\n"
}

echo "/* This file is autogenerated by wordlists2c.sh, do not edit */"
echo
echo "#include \"wordlists.h\""

# wordlist_slip0039 on 2020-05-31 available from
#    https://github.com/satoshilabs/slips/raw/master/slip-0039/wordlist.txt
format_wordlist slip0039 \
	bcc4555340332d169718aed8bf31dd9d5248cb7da6e5d355140ef4f1e601eec3 1024

# wordlist_bip0039_english on 2020-05-31 available from
#    https://github.com/bitcoin/bips/raw/master/bip-0039/english.txt
format_wordlist bip0039_english \
	2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda 2048
format_wordlist diceware_german \
	86eaf47b43df1c7f926b1d2f4cc724141de626c601a32562f28ec204fb3b9607 7776
format_wordlist diceware_dutch \
	7086f199c1366aff1f48257c9861574b485ad3763442adcaf4fbbd16bce5276c 7776
format_wordlist base16 \
	0bedb386a64d361e65bdf47702cdde4ad44491960c28589bdedd29916a0581d6 16
format_wordlist base58 \
	7c67430686b77fac7051d8ea4372dcc02884533134544a3355caa5967a0687d1 58
format_wordlist bech32 \
	cf0555e8aab8ffc79a19bbc1eb492f27e0d93f35a931cf31be665c9921032ed4 32

INIT="$INIT}\n";
echo $INIT
