#!/bin/sh
#
# wordlist2c.sh - shellscript to translate wordlist.txt to c file
#
# Copyright 2020 Rik Snel <rik@snel.it>
#
# This file is part of slip0039.
#
# slip0039 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# slip0039 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with slip0039.  If not, see <https://www.gnu.org/licenses/>.

WORDLIST_SLIP0039=wordlist_slip0039.txt
WORDLIST_SLIP0039_SHA256=bcc4555340332d169718aed8bf31dd9d5248cb7da6e5d355140ef4f1e601eec3

fatal() {
	echo $1 >&2
	exit 1
}

if [ "$#" != "0" ]; then
	fatal "wrong number of arguments given"
fi

# filename_prefix sha256 lines
format_wordlist() {
	FILENAME=$1.txt
	if [ ! -f "$FILENAME" ]; then
		fatal "file \"$FILENAME\" not found"
	fi

	if [ ! -r "$FILENAME" ]; then
		fatal "file \"$FILENAME\" is not readable"
	fi

	if [ "$2" != `sha256sum "$FILENAME" | cut -f 1 -d ' '` ]; then
		fatal "sha256sum of \"$FILENAME\" does not match"
	fi

	NUM=`wc -l $FILENAME | cut -f 1 -d ' '`
	if [ "$NUM" != "$3" ]; then
		fatal "file $FILENAME has $NUM lines, when $3 lines were expected"
	fi

	echo
	echo wordlist_t $1 = {
	echo "\t.no_words = $3,"
	echo "\t.words = (char *[]){"
	head -n -1 $FILENAME | sed "s/^/\t\t\"/;s/\$/\",/"
	tail -n 1 $FILENAME | sed "s/^/\t\t\"/;s/\$/\"/"
	echo "\t}"
	echo "};"
}

echo "/* This file is autogenerated by wordlists2c.sh, do not edit */"
echo
echo "#include \"wordlist.h\""

# wordlist_slip0039 on 2020-05-31 available from
#    https://github.com/satoshilabs/slips/raw/master/slip-0039/wordlist.txt
format_wordlist wordlist_slip0039 \
	bcc4555340332d169718aed8bf31dd9d5248cb7da6e5d355140ef4f1e601eec3 1024

# wordlist_bip0039_english on 2020-05-31 available from
#    https://github.com/bitcoin/bips/raw/master/bip-0039/english.txt
format_wordlist wordlist_bip0039_english \
	2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda 2048

#if [ ! -f "$WORDLIST_SLIP0039" ]; then
#	echo file \"$WORDLIST_SLIP0039\" not found >&2
#	exit 1
#fi
#if [ ! -r "$WORDLIST_SLIP0039" ]; then
#	echo file \"$WORDLIST_SLIP0039\" is not readable >&2
#	exit 1
#fi

#if [ "$WORDLIST_SLIP0039_SHA256" != `sha256sum "$WORDLIST_SLIP0039" | cut -f 1 -d ' '` ]; then
#	echo sha256sum of \"$WORDLIST_SLIP0039\" does not match >&2
#	exit 1
#fi

#get the number of words
#NUM=`wc -l $WORDLIST_SLIP0039 | cut -f 1 -d ' '`
#if [ "$NUM" != 1024 ]; then
#	echo file \"$WORDLIST_SLIP0039\" has an unexpected number of lines $NUM vs the expected 1024 >&2
#	exit 1
#fi

#echo
#echo char \*wordlist_slip0039[1024] = {
#head -n -1 $WORDLIST_SLIP0039 | sed "s/^/\t\"/;s/\$/\",/"
#tail -n 1 $WORDLIST_SLIP0039 | sed "s/^/\t\"/;s/\$/\"/"
#echo }\;
