#!/bin/sh
#
# wordlist2c.sh - shellscript to translate wordlist.txt to c file
#
# Copyright 2020 Rik Snel <rik@snel.it>
#
# This file is part of slip0039.
#
# slip0039 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# slip0039 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with slip0039.  If not, see <https://www.gnu.org/licenses/>.

WORDLIST_SHA256=bcc4555340332d169718aed8bf31dd9d5248cb7da6e5d355140ef4f1e601eec3

if [ "$#" != "1"  ]; then
	echo wrong number of arguments given >&2
	exit 1
fi

if [ ! -f "$1" ]; then
	echo file \"$1\" not found >&2
	exit 1
fi
if [ ! -r "$1" ]; then
	echo file \"$1\" is not readable >&2
	exit 1
fi

if [ "$WORDLIST_SHA256" != `sha256sum "$1" | cut -f 1 -d ' '` ]; then
	echo sha256sum of \"$1\" does not match >&2
	exit 1
fi

#get the number of words
NUM=`wc -l $1 | cut -f 1 -d ' '`
if [ "$NUM" != 1024 ]; then
	echo file \"$1\" has an unexpected number of lines $NUM vs the expected 1024 >&2
	exit 1
fi

echo '/* This file is autogenerated from wordlist.txt, do not edit */' 
echo
echo char \*wordlist[1024] = {
head -n -1 $1 | sed "s/^/\t\"/;s/\$/\",/"
tail -n 1 $1 | sed "s/^/\t\"/;s/\$/\"/"
echo }\;
