#!/bin/sh
#
# wordlists2c.sh - shellscript to translate wordlist.txt to c file
#
# Copyright 2020 Rik Snel <rik@snel.it>
#
# This file is part of slip0039.
#
# slip0039 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# slip0039 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with slip0039.  If not, see <https://www.gnu.org/licenses/>.

fatal() {
	echo $1 >&2
	exit 1
}

if [ "$#" != "0" ]; then
	fatal "wrong number of arguments given"
fi

# filename_prefix sha256 lines
format_wordlist() {
	FILENAME=$1.txt
	if [ ! -f "$FILENAME" ]; then
		fatal "file \"$FILENAME\" not found"
	fi

	if [ ! -r "$FILENAME" ]; then
		fatal "file \"$FILENAME\" is not readable"
	fi

	if [ "$2" != `sha256sum "$FILENAME" | cut -f 1 -d ' '` ]; then
		fatal "sha256sum of \"$FILENAME\" does not match"
	fi

	NUM=`wc -l $FILENAME | cut -f 1 -d ' '`
	if [ "$NUM" != "$3" ]; then
		fatal "file $FILENAME has $NUM lines, when $3 lines were expected"
	fi

	echo
	echo char \*$1[$3] = {
	head -n -1 $FILENAME | sed "s/^/\t\"/;s/\$/\",/"
	tail -n 1 $FILENAME | sed "s/^/\t\"/;s/\$/\"/"
	echo }\;
}

echo "/* This file is autogenerated by wordlists2c.sh, do not edit */"

format_wordlist wordlist_slip0039 \
	bcc4555340332d169718aed8bf31dd9d5248cb7da6e5d355140ef4f1e601eec3 1024
format_wordlist wordlist_bip0039_english \
	2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda 2048
format_wordlist wordlist_diceware_german \
	86eaf47b43df1c7f926b1d2f4cc724141de626c601a32562f28ec204fb3b9607 7776
